model = "gpt-5.4"
approval_policy = "on-request"
# model_provider = "hiapi"
# model_provider = "gptplus5"
model_provider = "sub2api"

[model_providers.hiapi]
name = "OpenAI using LLM proxy"
base_url = "http://38.246.251.165:3003/v1"
env_key = "HIAPI_KEY"

[model_providers.gptplus5]
name = "OpenAI using LLM proxy"
base_url = "http://az.gptplus5.com/v1"
env_key = "GPTPLUS_KEY"

[model_providers.sub2api]
name = "sub2api"
base_url = "http://www.lazycoder.cloud-ip.cc"
env_key = "SUB2API"
wire_api = "responses"
requires_openai_auth = true

